### ISSUE TITLE
\Documents\RoadCaptain\ folder isn't created while saving + Error

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#24] opened 2022-04-14 07:21 UTC
According to #19 , Saving a route  open \Documents\ directory but do no create a specific folder \RoadCaptain\ avoiding to have all saved route files directly inside \Documents\

I also have another issue related to #23
![Screenshot_22](https://user-images.githubusercontent.com/99896027/163334473-d9408fd7-802e-47a5-8d1b-ddcc9e24f474.png)

**Comment by sandermvanvliet** [comment] 2022-04-14 07:34
That’s actually by design and generally a good practise to not create arbitrary folders without asking the user.

I do know that lots of applications _do_ create their folders like this so it’s something to consider.

Typically you would create the RoadCaptain folder yourself if it doesn’t exist.

**Comment by sandermvanvliet** [comment] 2022-04-21 21:00
I’m going to close this issue in favour of #27 
When that’s fixed, Road Captain will look in the last folder by default and if you create one for RoadCaptain specifically it should sort out this issue

**Closed by sandermvanvliet** 2022-04-21 21:00 UTC
